-- MySQL Script generated by MySQL Workbench
-- 11/08/16 01:31:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema igreja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema igreja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `igreja` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `igreja` ;

-- -----------------------------------------------------
-- Table `igreja`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `igreja`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `level` INT NOT NULL COMMENT '',
  `surname` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igreja`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `igreja`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igreja`.`devotional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `igreja`.`devotional` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `body` LONGTEXT NOT NULL COMMENT '',
  `category_id` INT NOT NULL COMMENT '',
  `image` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_devotional_category_idx` (`category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_devotional_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `igreja`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
